### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [rcg916/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by rcg916** [comment]
Hi Ken,
Thanks for taking a look at my code! I have looked into the mobile meta tag, and I think I have solved the issue. I added `<meta name="viewport" content="width=device-width, initial-scale=1">` into the header section of my application.html.erb file.

Please let me know if I went the wrong direction with it. Thanks again.

**Comment by kenmazaika** [comment]
This looks like the perfect code to add to the file.  Thumbs up!  :+1:
